Hardcode the default "snyk-secret"
redhat-appstudio/build-definitions pull request #409
Opened 2023-05-23 15:01 UTC by sbose78

* The name of the secret would always be `snyk-secret`
<img width="768" alt="image" src="https://github.com/redhat-appstudio/build-definitions/assets/545280/a605d51b-cf48-4d16-b057-e5ef5f3e400c">

* The volume is set to 'optional: true' which means the absence of the `secret` wouldn't cause a failure ?

2023-05-23 15:15 UTC, enarha commented
I guess we can also remove the pipelines/core-services/snyk-secret.yaml patch?

2023-05-23 15:16 UTC, enarha commented on task/sast-snyk-check/0.1/sast-snyk-check.yaml
> +      default: snyk-secret
maybe snyk-shared-secret?

2023-05-23 15:22 UTC, dirgim commented
If we want to always attempt to run the `sast-synk-check` task, I think we will need to silence the error message that happens when trying to read the secret [here](https://github.com/redhat-appstudio/build-definitions/blob/c31f6ad4939f52b30b10331097a21a0d03ca1745/task/sast-snyk-check/0.1/sast-snyk-check.yaml#L45) because that seemed to be a point of confusion for users.

2023-05-30 16:00 UTC, sbose78 commented
@dirgim Maybe we should update the message here to reflect that this is an opt-in
"echo "SNYK_TOKEN not defined. Create $SNYK_SECRET secret with key containing Snyk token." | tee stdout.txt"

2023-05-30 16:05 UTC, sbose78 commented
This also means we'd have to update the name of the secret used by the services on infra-deployments ?

2023-06-22 15:12 UTC, sbose78 commented
To make things easier, I added the name of the secret "snyk-secret" in the message.

2023-06-23 06:03 UTC, Michkov commented
/retest

2023-06-23 08:14 UTC, Michkov commented on task/sast-snyk-check/0.1/sast-snyk-check.yaml
> +          echo "If you wish to use the Snyk code SAST task, please create a secret named snyk-secret with the key containing the Snyk token." | tee stdout.txt
please provide exact key name.

2023-06-23 08:20 UTC, Michkov requested changes
Should be also https://github.com/redhat-appstudio/build-definitions/blob/a383e661bbf64c1500efc1cfe2b01f4936ec2a8b/pipelines/template-build/template-build.yaml#L53 updated or removed?

2023-06-28 06:15 UTC, Michkov commented on pipelines/template-build/template-build.yaml
> -      default: ""
With deletion of this you need to delete references -> lines 203 and 213.

2023-06-29 09:02 UTC, Michkov approved these changes

2023-07-03 09:28 UTC, dirgim approved these changes
LGTM

2023-07-18 06:39 UTC, Michkov commented
/retest

2023-07-18 16:04 UTC, flacatus commented
/retest

2023-07-18 16:06 UTC, sbose78 commented
/retest

2023-07-19 05:45 UTC, merged