PLNSRVCE-255 - sharedSecret for infra-deployments update
redhat-appstudio/build-definitions pull request #95
Opened 2022-05-11 13:18 UTC by mbharatk

Instead of creating a secret in each service namespace, a shared secret is defined. (https://github.com/redhat-appstudio/infra-deployments/pull/350)
this PR adds the shared secret config to update-infra-deployments task, which can be used to update infra-deployments.

2022-05-11 18:03 UTC, gabemontero commented
this should not merge until we merge https://github.com/redhat-appstudio/infra-deployments/pull/349 minimally

we quite possibly will want also gate this on our sorting out of the 3 minute delay wrt permission application for the pipeline SA that 
@sbose78 @Michkov and I have been discussing in slack

let's see if 

/hold

is set up for this repo

2022-05-11 18:04 UTC, gabemontero commented
> 
> let's see if
> 
> /hold
> 
> is set up for this repo

does not look like it :-)

2022-05-12 01:58 UTC, mbharatk commented
@gabemontero Sure, we could keep this on hold until the #349 is merged.

2022-05-12 09:08 UTC, Michkov requested changes

2022-05-12 09:08 UTC, Michkov commented on tasks/update-infra-deployments.yaml
> +          mountPath: /tmp/infra-deployments-pr-creator
do not use /tmp/ that could be handled differently then other dirs. Rather use `/secrets/deploy-key`

2022-05-12 09:08 UTC, Michkov commented on tasks/update-infra-deployments.yaml
> +          value: $(tmp/infra-deployments-pr-creator)/appstudio-staging-ci
should be path directly (not evaluated as `$()`) -> `value: /secrets/deploy-key/appstudio-staging-ci`

2022-05-12 09:08 UTC, Michkov commented on tasks/update-infra-deployments.yaml
>          cp -R "${WORKSPACE_SSH_DIRECTORY_PATH}" ~/.ssh
`${WORKSPACE_SSH_DIRECTORY_PATH}` has been removed, so it should be replaced by `/secrets/deploy-key`

2022-05-12 09:08 UTC, Michkov commented on tasks/update-infra-deployments.yaml
>        env:
the volume is not mounted in this step

2022-05-12 09:32 UTC, Michkov commented on tasks/update-infra-deployments.yaml
>      - name: deploy-key
Also please add comment that the workspace is only as placeholder and can be removed after it will be removed from consumers.

2022-05-12 09:32 UTC, Michkov commented on tasks/update-infra-deployments.yaml
>            'appstudio-staging-ci' - private key for appstudio-staging-ci Github app
Put this description as comment to the volume

2022-05-12 12:16 UTC, Michkov requested changes

2022-05-13 05:33 UTC, Michkov approved these changes

2022-05-13 05:34 UTC, merged